<div id="dlg-edit" class="easyui-dialog" style="width:400px;height:320px;padding:10px 20px"
    closed="true" modal="true" buttons="#dlg-edit-buttons" title="编辑表单">
    <form id="fm-edit" method="post" action="<?php echo base_url('sys/user/post')?>" novalidate>
        <input type="hidden" name="actionxm" value="">
        <table class="fm-table" cellpadding="4px">
            <colgroup>
                <col width="80px" /><col width="*" />
            </colgroup>
            <tr>
                <td>用户ID:</td>
                <td><input class="text" name="user_id" value="" readonly></td>
            </tr>
            <tr>
                <td>用户账号:</td>
                <td><input class="text" name="user_name" required="true"></td>
            </tr>
            <tr>
                <td>用户密码:</td>
                <td><input class="text" name="pwd" type="password" value="" required="true"></td>
            </tr>
            <tr>
                <td>真实姓名:</td>
                <td><input class="text" name="true_name" required="true"></td>
            </tr>
            <tr>
                <td>邮箱:</td>
                <td><input class="text" name="email" required="true"></td>
            </tr>
            <tr>
                <td>岗位职责:</td>
                <td><input class="text" name="uposition"></td>
            </tr>
            <tr>
                <td>是否管理员:</td>
                <td>
                    <input type="radio" class="radio" name="is_admin" value="0" checked id="is_admin_0"><label for="is_admin_0">普通用户</label>
                    <input type="radio" class="radio" name="is_admin" value="1" id="is_admin_1"><label for="is_admin_1">超级管理员</label>
                </td>
            </tr>
        </table>
    </form>
</div>
<div id="dlg-edit-buttons">
    <button class="easyui-linkbutton w90" iconCls="icon-ok" onclick="do_save()">确定</button>
    <button class="easyui-linkbutton w90" iconCls="icon-cancel" onclick="javascript:$('#dlg-edit').dialog('close')">取消</button>
</div>
