<!DOCTYPE html>
<html>
<head>
    <?php
    $this->load->view('/public/linker',array(
        'css'=>array('easyui_themes/color')
    ));
    ?>
    <style type="text/css">
    body{overflow:hidden;}
    #panel-login{
        position:absolute;
        width:460px;
        height:260;
        left:50%;
        top:40%;
        margin:-120px 0 0 -230px;
    }
    .icon-help {
        background-position: left center;
        padding-left: 20px;
        font-size: 14px;
        color: red;
    }
    </style>
</head>
<body>
    <div id="panel-login">
        <div class="easyui-panel" title="xcms发布系统" data-options="tools:'#tt'" style="width:100%;height:260px;padding:50px 40px 0 40px;">
            <form id="fm-login" action="<?php echo base_url('login/sign_in');?>" method="post">
                <table class="fm-table" cellpadding="12px">
                <colgroup><col width="60px" /><col width="*" /></colgroup>
                <tr>
                    <td>账号：</td>
                    <td><input class="text" name="user_name" id="user_name" value="" data-options="required:true"  autocomplete="off"></td>
                </tr>
                <tr>
                    <td>密码：</td>
                    <td><input class="text" type="password" name="pwd" id="pwd" value=""  autocomplete="off"></td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align:right;">
                        <button type="button" class="easyui-linkbutton c8" style="width:120px;" onclick="javascript:do_submit();">登录</button>
                    </td>
                </tr>
                </table>
            </form>
        </div>
        <style>
        #ft a {
            color: black;
        }
        </style>
    </div>
    <script type="text/javascript">
    function do_submit(){
        $('#fm-login').form('submit', {
            onSubmit: function() {
                var user_name = $('#user_name').val();
                if(user_name=='') {
                    $.messager.alert('操作提示','请输入登录账号');
                    return false;
                }
            },
            success:function(data) {
                var result = $.parseJSON(data);
                if(result['success']==false) {
                    $.messager.alert('操作提示', result['data']);
                    return false;
                } else {
                    var cur_url = window.location.href;
                    var anchor = '';
                    if(cur_url.indexOf('#')>=0) {
                        anchor = cur_url.substr(cur_url.indexOf('#'));
                    }
                    window.location.href = '<?php echo $referer;?>' + anchor;
                }
            }
        });
    }
    $(document).ready(function() {
        $('#user_name').focus();

        // Enter事件
        $("input").keydown(function(e) {
            var curKey = e.which;
            if(curKey == 13) {
                do_submit();
                return false;
            }
        });
    });
    </script>
</body>
</html>
