<!DOCTYPE html>
<html>
<head>
    <?php
        $this->load->view('/public/linker',array(
            'css'=>array(),
            'js' =>array(),
        ));
        $ctrl_url = base_url('publish/site');
    ?>
    <style>
    .split-line {
        color: #ccc;
    }
    .datagrid-sort-asc .datagrid-sort-icon, .datagrid-sort-desc .datagrid-sort-icon {
        padding: 0px;
    }
    .tip {
        color: #337ab7;
    }
    </style>
</head>
<body>
    <table id="dg" class="easyui-datagrid" title="站点列表"
           fit="true" border="false" plain="true"
           toolbar="#toolbar" multiSort="true"
           rownumbers="false" pagination="true" pageList="[50,100,150,200]" pageSize="50"
           singleSelect="true" remote>
        <thead>
            <tr>
                <th data-options="sortable:true,field:'site_id',width:50">站点ID</th>
                <th data-options="sortable:true,field:'site_name',width:100">名称</th>
                <th data-options="sortable:true,field:'alias_name',width:100">别名</th>
                <th data-options="sortable:true,field:'domain',width:180">域名</th>
                <th data-options="sortable:true,field:'description',width:200">描述</th>
                <th data-options="sortable:true,field:'create_user',width:80">创建账号</th>
                <th data-options="sortable:true,field:'create_time',width:120">创建时间</th>
                <th data-options="sortable:true,field:'update_user',width:80">更新账号</th>
                <th data-options="sortable:true,field:'update_time',width:120">更新时间</th>
                <th data-options="sortable:false,field:'vid',width:80" formatter="format_operator">操作</th>
            </tr>
        </thead>
    </table>

    <div id="toolbar">
        <button class="easyui-linkbutton" iconCls="icon-add"    plain="true" onclick="open_insert()">添加</button>
        <button class="easyui-linkbutton" iconCls="icon-edit"   plain="true" onclick="open_update()">修改</button>
        <button class="easyui-linkbutton" iconCls="icon-cancel" plain="true" onclick="do_delete()">删除</button>
    </div>

    <?php $this->load->view('publish/site_edit');?>

    <script type="text/javascript">
    $(function() {
        window.setTimeout(function() {
            var obj = new Object();
            obj.actionxm = 'search';
            obj.rs = $('#fm-search').form('getData');
            $('#dg').datagrid({
                url: "<?php echo $ctrl_url.'/get'?>",
                method: "post",
                queryParams: obj
            });
        }, 100);
    })

    // 打开添加窗口
    function open_insert(){
        $('#fm-edit').form('clear').form('load',{actionxm:'insert',site_id:'系统编号'});
        $('#dlg-edit').dialog('setTitle','站点添加').dialog('open');
    }

    // 打开更新窗口
    function open_update(){
        var info=$('#dg').datagrid('getSelected');
        if(info==null){
            $.messager.alert('操作提示','请选择需要编辑的站点!','warning');
            return;
        }
        var fm_data={
            actionxm: 'update',
            site_id: info.site_id,
            site_name: info.site_name,
            alias_name: info.alias_name,
            domain: info.domain,
            description: info.description
        };
        $('#fm-edit').form('load',fm_data);
        $('#dlg-edit').dialog('setTitle','站点编辑').dialog('open');
    }

    // 保存操作
    function do_save(){
        $('#fm-edit').form('submit',{
            onSubmit: function(){
                return $(this).form('validate');
            },
            success: function(result){
                var result = eval('('+result+')');
                if (result.success==false){
                    $.messager.alert('操作提示',result.data,'warning');
                } else {
                    $('#dlg-edit').dialog('close');
                    $('#dg').datagrid('reload');
                }
            }
        });
    }

    // 删除操作
    function do_delete(){
        var info=$('#dg').datagrid('getSelected');
        if(info==null){
            $.messager.alert('操作提示','请选择需要删除的站点!','warning');
            return;
        }
        $.messager.confirm('操作提示','你确定要删除此站点吗?',function(r){
            if (r){
                $.post('<?php echo $ctrl_url."/post"?>',{site_id:info.site_id,actionxm:'delete'},function(result){
                    if (result.success){
                        $('#dg').datagrid('reload');
                    } else {
                        $.messager.alert('操作提示','删除成功');
                    }
                },'json');
            }
        });
    }

    // 格式化操作
    function format_operator(val, row) {
        var rtn = '';
        if(val>0) {
            rtn = '<button type="button" class="easyui-linkbutton" onclick="jump_choose(\''+row.alias_name+'\', '+val+')">选择</button>';
        }
        return rtn;
    }

    // 跳转到模板
    function jump_choose(title, sid) {
        var url = 'publish/template/slist/?sid=' + sid;
        openSubTab('站点-'+title, url);
    }
    </script>
</body>
</html>
